version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
     - '5432:5432'
    volumes:
      - ./seed/seed.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql